x-api: &api
    image: rinha-c-iouring:local
    build:
      context: .
      dockerfile: Dockerfile.iouring
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

services:
  api1:
    <<: *api
    ports:
      - "9999:8080"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "300MB"

  api2:
    <<: *api
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "50MB"
