x-api: &api
    image: ghcr.io/renatograsso10/rinha-backend-2026-c-exact@sha256:9e3eddbe3f887f01f4b1e6f8dcffbe2653a0d72687eb0c90fc67bb399052da5f
    environment:
      SOCKET_PATH: /sockets/api.sock
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

services:
  haproxy:
    image: haproxy:3.3
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  api1:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api1.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

  api2:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api2.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

volumes:
  sockets:
