x-api: &api
    image: ghcr.io/renatograsso10/rinha-backend-2026-go-runtime@sha256:c23394e3a1f728451064278bd8c22917d1e8dfb99a8b202243781df3de0ab987
    environment:
      SOCKET_PATH: /sockets/api.sock
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

services:
  haproxy:
    image: haproxy:3.3
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  api1:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api1.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

  api2:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api2.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

volumes:
  sockets:
