x-api: &api
    image: ghcr.io/renatograsso10/rinha-backend-2026-go-runtime@sha256:3f829e87ec54596b470d6fbe86a7c1ff9c26258b67429409d80db5e6d1594fb0
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

services:
  api1:
    <<: *api
    ports:
      - "9999:8080"
    deploy:
      resources:
        limits:
          cpus: "0.90"
          memory: "250MB"

  api2:
    <<: *api
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "100MB"
