x-api: &api
    image: rinha-c-epoll:local
    build:
      context: .
      dockerfile: Dockerfile.c
    environment:
      SOCKET_PATH: /sockets/api.sock
    volumes:
      - sockets:/sockets
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

services:
  proxy:
    image: rinha-proxy:local
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  api1:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api1.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

  api2:
    <<: *api
    environment:
      SOCKET_PATH: /sockets/api2.sock
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

volumes:
  sockets:
