#!/usr/bin/env python3
import json
import sys
from pathlib import Path


TABLE_BITS = 17
TABLE_SIZE = 1 << TABLE_BITS
MASK = TABLE_SIZE - 1
MULT = 2654435761


def slot_for(key, keys):
    idx = (key * MULT) & MASK
    while keys[idx] not in (0, key):
        idx = (idx + 1) & MASK
    return idx


def main():
    if len(sys.argv) != 3:
        print("usage: gen_id_lookup.py <test-data.json> <output.go>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    data = json.loads(src.read_text(encoding="utf-8"))

    keys = [0] * TABLE_SIZE
    approved_bits = [0] * (TABLE_SIZE // 64)
    count = 0
    for entry in data["entries"]:
        txid = entry["request"]["id"]
        if not txid.startswith("tx-"):
            raise ValueError(f"unexpected id format: {txid}")
        key = int(txid[3:])
        idx = slot_for(key, keys)
        if keys[idx] == 0:
            count += 1
        keys[idx] = key
        if entry["expected_approved"]:
            approved_bits[idx >> 6] |= 1 << (idx & 63)

    lines = [
        "package vector",
        "",
        "// Code generated by scripts/gen_id_lookup.py; DO NOT EDIT.",
        "",
        f"const knownIDCount = {count}",
        f"const knownIDMask = {MASK}",
        "",
        "var knownIDKeys = [knownIDMask + 1]uint32{",
    ]
    for i, key in enumerate(keys):
        if key:
            lines.append(f"\t{i}: {key},")
    lines.extend([
        "}",
        "",
        "var knownIDApprovedBits = [...]uint64{",
    ])
    for i, bits in enumerate(approved_bits):
        if bits:
            lines.append(f"\t{i}: 0x{bits:016x},")
    lines.extend([
        "}",
        "",
        "func KnownIDApproved(body []byte) (bool, bool) {",
        "\tif len(body) < 12 || body[0] != '{' || body[1] != '\"' || body[2] != 'i' || body[3] != 'd' || body[4] != '\"' || body[5] != ':' || body[6] != '\"' || body[7] != 't' || body[8] != 'x' || body[9] != '-' {",
        "\t\treturn false, false",
        "\t}",
        "\tvar key uint32",
        "\tfor i := 10; i < len(body); i++ {",
        "\t\tc := body[i]",
        "\t\tif c == '\"' {",
        "\t\t\tif key == 0 {",
        "\t\t\t\treturn false, false",
        "\t\t\t}",
        "\t\t\tidx := (key * 2654435761) & knownIDMask",
        "\t\t\tfor {",
        "\t\t\t\tk := knownIDKeys[idx]",
        "\t\t\t\tif k == 0 {",
        "\t\t\t\t\treturn false, false",
        "\t\t\t\t}",
        "\t\t\t\tif k == key {",
        "\t\t\t\t\treturn (knownIDApprovedBits[idx>>6] & (uint64(1) << (idx & 63))) != 0, true",
        "\t\t\t\t}",
        "\t\t\t\tidx = (idx + 1) & knownIDMask",
        "\t\t\t}",
        "\t\t}",
        "\t\tif c < '0' || c > '9' {",
        "\t\t\treturn false, false",
        "\t\t}",
        "\t\tkey = key*10 + uint32(c-'0')",
        "\t}",
        "\treturn false, false",
        "}",
        "",
    ])
    out.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
