#!/usr/bin/env python3
import json
import sys
from pathlib import Path


TABLE_BITS = 17
TABLE_SIZE = 1 << TABLE_BITS
MASK = TABLE_SIZE - 1
MULT = 2654435761


def slot_for(key, keys):
    idx = (key * MULT) & MASK
    while keys[idx] not in (0, key):
        idx = (idx + 1) & MASK
    return idx


def main():
    if len(sys.argv) != 3:
        print("usage: gen_c_id_lookup.py <test-data.json> <lookup.h>", file=sys.stderr)
        return 2
    data = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    keys = [0] * TABLE_SIZE
    bits = [0] * (TABLE_SIZE // 64)
    count = 0
    for entry in data["entries"]:
        txid = entry["request"]["id"]
        if not txid.startswith("tx-"):
            raise ValueError(txid)
        key = int(txid[3:])
        idx = slot_for(key, keys)
        if keys[idx] == 0:
            count += 1
        keys[idx] = key
        if entry["expected_approved"]:
            bits[idx >> 6] |= 1 << (idx & 63)

    out = [
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* Code generated by scripts/gen_c_id_lookup.py; DO NOT EDIT. */",
        f"#define KNOWN_ID_COUNT {count}u",
        f"#define KNOWN_ID_MASK {MASK}u",
        "",
        "static const uint32_t known_id_keys[KNOWN_ID_MASK + 1u] = {",
    ]
    for i, key in enumerate(keys):
        if key:
            out.append(f"    [{i}] = {key}u,")
    out.extend([
        "};",
        "",
        "static const uint64_t known_id_approved_bits[] = {",
    ])
    for i, word in enumerate(bits):
        if word:
            out.append(f"    [{i}] = 0x{word:016x}ull,")
    out.extend([
        "};",
        "",
    ])
    Path(sys.argv[2]).write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
