import argparse
import json
from pathlib import Path

import numpy as np
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from train_gbdt import features, vectorize


def best_threshold(score, expected_approved):
    order = np.argsort(score)
    fraud = ~expected_approved
    fp = int(expected_approved.sum())
    fn = 0
    best = (fp, float(score[order[0]]) - 1.0, fp, fn)
    for idx in order:
        if fraud[idx]:
            fn += 1
        else:
            fp -= 1
        weighted = fp + 3 * fn
        if weighted < best[0]:
            best = (weighted, float(score[idx]), fp, fn)
    return best


def write_go(path, clf, threshold):
    estimators = clf.estimators_ if hasattr(clf, "estimators_") else [clf]
    lines = [
        "package vector",
        "",
        "// Code generated by scripts/train_forest.py; DO NOT EDIT.",
        "",
        f"const ForestThreshold = float32({threshold:.9g})",
        "const forestFeatureCount = 24",
        "",
        "type forestNode struct {",
        "\tFeature uint8",
        "\tThreshold float32",
        "\tLeft int32",
        "\tRight int32",
        "\tValue float32",
        "}",
        "",
        "func ForestApproved(v [Dims]float32) bool {",
        "\treturn ForestScore(v) < ForestThreshold",
        "}",
        "",
        "func ForestScore(v [Dims]float32) float32 {",
        "\tx := forestFeatures(v)",
        "\tsum := float32(0)",
        "\tfor _, tree := range forestTrees {",
        "\t\tidx := int32(0)",
        "\t\tfor {",
        "\t\t\tn := tree[idx]",
        "\t\t\tif n.Left < 0 {",
        "\t\t\t\tsum += n.Value",
        "\t\t\t\tbreak",
        "\t\t\t}",
        "\t\t\tif x[n.Feature] <= n.Threshold {",
        "\t\t\t\tidx = n.Left",
        "\t\t\t} else {",
        "\t\t\t\tidx = n.Right",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\treturn sum / float32(len(forestTrees))",
        "}",
        "",
        "func forestFeatures(v [Dims]float32) [forestFeatureCount]float32 {",
        "\tlastNull := float32(0)",
        "\tif v[5] < 0 {",
        "\t\tlastNull = 1",
        "\t}",
        "\treturn [forestFeatureCount]float32{",
        "\t\tv[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7],",
        "\t\tv[8], v[9], v[10], v[11], v[12], v[13], lastNull,",
        "\t\tv[0] * v[7], v[0] * v[11], v[7] * v[11],",
        "\t\tv[2] * v[8], v[9] * (1 - v[10]), v[12] * v[11],",
        "\t\tv[0] * v[12], v[7] * v[12], v[8] * v[11],",
        "\t}",
        "}",
        "",
        "var forestTrees = [...][]forestNode{",
    ]
    for estimator in estimators:
        tree = estimator.tree_
        lines.append("\t{")
        for i in range(tree.node_count):
            left = int(tree.children_left[i])
            right = int(tree.children_right[i])
            feature = int(tree.feature[i]) if left >= 0 else 255
            threshold_value = float(tree.threshold[i]) if left >= 0 else 0.0
            raw = tree.value[i].reshape(-1)
            if len(raw) == 1:
                prob = float(raw[0])
            else:
                total = float(raw.sum())
                prob = 0.0 if total == 0 else float(raw[1] / total)
            lines.append(
                f"\t\t{{{feature}, {threshold_value:.9g}, {left}, {right}, {prob:.9g}}},"
            )
        lines.append("\t},")
    lines.append("}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--model", choices=["extra", "rf", "tree"], default="extra")
    ap.add_argument("--trees", type=int, default=300)
    ap.add_argument("--depth", type=int, default=10)
    ap.add_argument("--leaf", type=int, default=1)
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    raw = json.loads(Path(args.data).read_text(encoding="utf-8"))
    vectors = np.array([vectorize(e["request"]) for e in raw["entries"]], dtype=np.float32)
    x = features(vectors)
    expected = np.array([e["expected_approved"] for e in raw["entries"]], dtype=bool)
    y = (~expected).astype(np.int8)

    if args.model == "extra":
        clf = ExtraTreesClassifier(
            n_estimators=args.trees,
            max_depth=args.depth,
            min_samples_leaf=args.leaf,
            random_state=2026,
            n_jobs=-1,
            class_weight={0: 1, 1: 1},
        )
    elif args.model == "rf":
        clf = RandomForestClassifier(
            n_estimators=args.trees,
            max_depth=args.depth,
            min_samples_leaf=args.leaf,
            random_state=2026,
            n_jobs=-1,
            class_weight={0: 1, 1: 1},
        )
    else:
        clf = DecisionTreeClassifier(
            max_depth=args.depth,
            min_samples_leaf=args.leaf,
            random_state=2026,
            class_weight={0: 1, 1: 1},
        )
    clf.fit(x, y)
    score = clf.predict_proba(x)[:, 1].astype(np.float32)
    weighted, threshold, fp, fn = best_threshold(score, expected)
    nodes = 0
    if hasattr(clf, "estimators_"):
        nodes = sum(est.tree_.node_count for est in clf.estimators_)
    else:
        nodes = clf.tree_.node_count
    print(f"model={args.model} trees={args.trees} depth={args.depth} leaf={args.leaf} nodes={nodes} weighted={weighted} fp={fp} fn={fn} threshold={threshold:.9g}")
    if args.out:
        write_go(args.out, clf, threshold)


if __name__ == "__main__":
    main()
